### ISSUE TITLE
Add MercadoPago Payment Portal

### ISSUE THREAD

**Issue by Istevu** [AtoroTech/AtoroDash#100]
One suggestion I have is to add the Mercado Pago payment portal when possible.

**Comment by NaysKutzu** [comment]
Yeah this is a good idea but idk if i will waste my time on coding it since it takes a lot of time to write another payment gataway!

**Comment by NaysKutzu** [comment]
Sorry i can't create an account there and i do not understand shit you will have to stick to stripe or paypal :(!
