### ISSUE TITLE
Anyone using HolaClient has gotten their info stolen, we highly advise resetting everything and avoiding HolaClient.

### ISSUE THREAD

**Issue by NaysKutzu** [AtoroTech/AtoroDash#86]
Archive Link: <https://github.com/nayskutzu/HolaClient/blob/latest/routes/structures/telemetry.js>

This was reported by @nyxalis on the popular discord server called [DontAbuse](https://discord.gg/dontabuse-1063534303109189702). 

Right now what you can do is reset everything that's in your settings.json and settings.yml files and then delete the telemetry.js file
We recommend you switch to another open-source client as soon as possible if you're still using Hola Client

@ItzGeoYT has seized the VM due to this.

This seems to extend to send the following data in addition:
- Pterodactyl admin key
- Pterodactyl client key
- Cloudflare api key (if setup)
- Email SMTP information (if setup)
- Bot token (if setup)
- linkvertise, shareus, linkpays & gyanilinks API keys (if setup)
- Discord bot application Secret, ClientID & Bot Token
- Discord log webhooks

We recommend that you switch over to MythicalDash!
https://github.com/mythicalltd/mythicaldash

If you don't want to use MythicalDash here are some more repos for you:
[FREE]
https://ctrlpanel.gg/
https://paymenter.org/
https://github.com/openheliactyl/heliactyl
[PAID]
https://www.whmcs.com/
https://www.blesta.com/

**Comment by ImGeorgiy** [comment]
Avoid using HolaClient.

**Comment by heyitslumi** [comment]
isn't heliactyl from another scammer

**Comment by heyitslumi** [comment]
+ its no longer maintained

**Comment by NaysKutzu** [comment]
Does it matter? no it i just so users can see what options there are

**Comment by Saboreq** [comment]
Cry more fking kids, code is open source so everybody agreed on this telemetry :'D

**Comment by ImGeorgiy** [comment]
Would you like getting a abuse report or sort of shit when you're a VPS
provider?

**Comment by NxyyLOL** [comment]
everyone stfu, holaclient was shitty to begin with lol

**Comment by boomerangBS** [comment]
thank's for this report

**Comment by NaysKutzu** [comment]
> thank's for this report

No problem it is my job to keep users safe!
